spring.datasource.url=jdbc:postgresql://localhost:5432/kyzmat_skud
spring.datasource.username=postgres
spring.datasource.password=postgres123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true